### ISSUE TITLE
Speech Command Dataset

### ISSUE THREAD

**Issue by wonyangcho** [SarthakYadav/leaf-pytorch#4]
Hi @SarthakYadav 

For Speech Command Classification, please let me know which dataset you used. 
I can't find csv file in speech_commands v0.02.tar.gz.

Thansk.

**Comment by SarthakYadav** [comment]
Yes, there isn't a .csv file in speech_commands v0.02.tar.gz, you have to make it yourself in the following format

```
files,labels
<filepath>,<string_label>
```

Another file you'll need is a label map: a .json dictionary that has `<string_label>:<class integer>` key value pairs.

I use this format for flexibility to not resort to a particular directory structure, as this contains full path of the dataset.

**Comment by wonyangcho** [comment]
@SarthakYadav  Thanks!
